tasks:
  - name: Run the stack
    init: |
      echo 'TODO: build project'
    command: |
       echo "CSRF_TRUSTED_ORIGINS = ['https://8001-${GITPOD_WORKSPACE_URL##https://}']" >> django-front/newproject/newproject/settings.py && docker-compose up 
