tasks:
  - name: Run the stack
    init: |
      echo 'TODO: build project'
    command: |
      echo "CSRF_TRUSTED_ORIGINS = ['${GITPOD_WORKSPACE_URL}']" >> django-front/newproject/newproject/settings.py && docker-compose up 
